openapi: 3.0.0
info:
  title: Shop API
  description: Jedi Shop App API Documentation
  version: 1.0.0

servers:
  - url: https://l8wsgw7aw5.execute-api.eu-west-1.amazonaws.com/dev
    description: Main server

components:
  schemas:
    Product:
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        imgUrl:
          type: string

      required:
        - id
        - name
        - price

paths:
  /products:
    get:
      summary: Returns a list of products.
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
             schema:
              type: array
              items:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      summary: Represents a product.
      description: >
            This resource represents an individual product in the system.
            Each product is identified by a numeric `id`.
      parameters:
      - name: id
        in: path
        description: Product ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Not found
          content:
            text/html:
              schema:
                type: string